CREATE DATABASE IF NOT EXISTS davetiye_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE davetiye_app;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS guests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 2,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN (1, 2, 3))
);

INSERT INTO users (username, password_hash)
VALUES ('uwedding', SHA2('OoAkk20071971', 256))
ON DUPLICATE KEY UPDATE username = username;
